components:
  gmmlib:
    branch: gmmlib
    clean_on_sync: true
    dest_dir: gmmlib
    repository: https://github.com/intel/gmmlib.git
    revision: intel-gmmlib-19.2.1
    type: git
  igc:
    branch: igc
    clean_on_sync: true
    dest_dir: igc
    repository: https://github.com/intel/intelgraphicscompiler
    revision: d162d4e9794c5ad6ca082358b4b88dcbf5bcb869
    type: git
  infra:
    branch: infra
    clean_on_sync: true
    dest_dir: infra
    revision: d76c695e200f898e89b209ba33269839bedc0a8a
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: c540fae1134269c52c15b62b6388b72583ead823
    type: git
  kmdaf:
    branch: kmdaf
    clean_on_sync: true
    dest_dir: kmdaf
    revision: a56f5ee43b873b74377d387e25d64cfebde5795d
    type: git
  libva:
    branch: libva
    clean_on_sync: true
    dest_dir: libva
    repository: https://github.com/intel/libva.git
    revision: c9bb65b
    type: git
  wdk:
    branch: wdk
    clean_on_sync: true
    dest_dir: wdk
    revision: 0dea8bf00d710a5d2da5d04eb5ae595d0df4ce47-1217
    type: git
converter: M-1262
version: '1'
